### LOGIN
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
	"email":"mickaelrkt20@gmail.com",
	"password":"mickael"
}


### register
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
	"username":"kol",
	"email":"kol@gmail.com",
	"password":"kol",
	"online": false
}


### get user by id
GET http://192.168.1.159:3000/api/users/getById/6814c26e8b7352b49bc32174


### get all user
GET http://localhost:3000/api/users/getAll


### send message
POST http://localhost:3000/api/message/send
Content-Type: application/json

{
	"senderId":"6835af67bf3973b387f784f4",
	"receiverId":"6835af87bf3973b387f784f6",
	"content":"Bonjour lty e"
}


### get message for another user
GET http://localhost:3000/api/message/6835af87bf3973b387f784f6/6835af67bf3973b387f784f4
